
spring:
  application:
    name: projeta-api

  datasource:
    url: jdbc:mysql://omega.ceuma.edu.br:49155/projeta_db
    username: projeta
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

server:
  servlet:
    context-path: /projeta-api